### ISSUE TITLE
Wrong public path

### ISSUE THREAD

**Issue by MichalPB1** [coremyslo/nuxt-icon-font#7]
Hi, I think I found a bug. In my project I changed a name of public directory via nuxt.config `dir.public` to `Public` and I see that build process do not take into that name. As a result, the font file is missing in the build

![obraz](https://github.com/coremyslo/nuxt-icon-font/assets/4595307/866b640f-b921-4d2e-9d11-b9b47a94075a)

![obraz](https://github.com/coremyslo/nuxt-icon-font/assets/4595307/bf278c77-e9f7-4fdb-8946-3a0f439a4e7a)

**Comment by coremyslo** [comment]
fixed in 1.1.0
https://github.com/coremyslo/nuxt-icon-font/pull/10
